# Docs - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Application Bug Report
description: Found a problem with the application itself (ie. bad file path handling, UX issue)? Help us improve it.
title: "[BUG]: "
labels: [Bug]
# assignees:
#   - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Important: Read First

        Please do not make support requests on GitHub. Our issue tracker is for tracking bugs and feature requests only
        If you need help configuring the emulator please use discord.

        If you are unsure, start with [discord](https://discord.com/invite/ghpjzNX7pH) or the [forums](https://forums.pcsx2.net/index.php).

        Please make an effort to make sure your issue isn't already reported.

        Do not create issues involving software piracy of BIOS or game files, our rules specifically prohibit this and your issue will be closed.


  - type: textarea
    id: desc
    attributes:
      label: Describe the Bug
      description: "A clear and concise description of what the bug is"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: "Steps to reproduce the behavior"
    validations:
      required: true
  - type: textarea
    id: expect
    attributes:
      label: Expected Behavior
      description: "A clear and concise description of what you expected to happen"
    validations:
      required: false
  - type: input
    id: rev
    attributes:
      label: PCSX2x6 Revision
      description: "Please ensure you are on the latest version before making an issue"
      placeholder: "Example: v2.5.374"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
      - Windows 11
      - Windows 10 (64bit)
      - Linux (64bit) - Specify distro below
      - macOS 26 (Tahoe)
      - macOS 15 (Sequoia)
      - macOS 14 (Sonoma)
      - macOS 13 (Ventura)
      - macOS 12 (Monterey)
      - macOS 11 (Big Sur)
    validations:
      required: true
  - type: input
    id: os-distro
    attributes:
      label: If Linux - Specify Distro
      placeholder: "Example: Arch"
    validations:
      required: false
  - type: textarea
    id: logsDumps
    attributes:
      label: "Logs & Dumps"
      description: |
        Please feel free to attach any logs here.
        If PCSX2x6 crashed, please post crash logs and the .dmp file (in a zip file) if appropriate.
    validations:
      required: false
