# Docs - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Emulation Bug Report
description: Problem in a game (ie. graphical artifacts, crashes)? Help us improve it.
title: "[BUG]: "
labels: [Bug]
# assignees:
#   - octocat
body:
  - type: markdown
    attributes:
      value: |
        ## Important: Read First

        If you need help configuring the emulator please contact us on discord.

        If you are unsure, start with [PCSX2x6 discord](https://discord.com/invite/ghpjzNX7pH).

        Please make an effort to make sure your issue isn't already reported.

        Keep in mind the developer of this fork can't help much with graphical issues, you may try asking for help on official PCSX2 channels/github/forums. but be warned they hate everything arcade related and you may be banned from wherever you ask

        Do not create issues involving software piracy of BIOS or ISO files, our rules specifically prohibit this and your issue will be closed.

        Do not Create issues asking for specific game support! first, check if your game has associated issue tickets on the [compatibility table](https://github.com/PS2Homebrew-arcade/pcsx2x6/issues/9). if there's none: ask on discord first

  - type: textarea
    id: desc
    attributes:
      label: Describe the Bug
      description: "A clear and concise description of what the bug is"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: "Steps to reproduce the behavior"
    validations:
      required: true
  - type: textarea
    id: expect
    attributes:
      label: Expected Behavior
      description: "A clear and concise description of what you expected to happen"
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## System Info

        Please make sure your system meets the requirements of base PCSX2 for OS version, CPU and GPU
        - [System Requirements](https://github.com/PCSX2/pcsx2#system-requirements).

        Performance issues as a result of not meeting our hardware requirements are not valid.

        
  - type: input
    id: rev
    attributes:
      label: PCSX2x6 Revision
      description: "please, try reproducing on latest available version before reporting"
      placeholder: "Example: v2.5.374"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
      - Windows 11
      - Windows 10 (64bit)
      - Linux (64bit) - Specify distro below
      - macOS 26 (Tahoe)
      - macOS 15 (Sequoia)
      - macOS 14 (Sonoma)
      - macOS 13 (Ventura)
      - macOS 12 (Monterey)
      - macOS 11 (Big Sur)
    validations:
      required: true
  - type: input
    id: os-distro
    attributes:
      label: If Linux - Specify Distro
      placeholder: "Example: Arch"
    validations:
      required: false
  - type: input
    id: cpu
    attributes:
      label: CPU
      placeholder: "Example: Intel i5 12400F"
    validations:
      required: true
  - type: input
    id: gpu
    attributes:
      label: GPU
      placeholder: "Example: Nvidia RTX 4060"
    validations:
      required: true
  - type: textarea
    id: gsSettings
    attributes:
      label: GS Settings
      description: "Any **non-default** settings for GS. If you don't want to list them out, please provide screenshots of your configuration window (including hw hacks if enabled)."
    validations:
      required: false
  - type: textarea
    id: emuSettings
    attributes:
      label: Emulation Settings
      description: |
        Any non-default core settings. If you don't want to list them out, please provide screenshots of your configuration window.

        Please note that defaults tend to work best.

        If you need to modify the settings manually to fix an issue , please state that explicitly.
    validations:
      required: false
  - type: textarea
    id: gsScreens
    attributes:
      label: GS Window Screenshots
      description: "If your issue is graphical in nature and you think screenshots will help illustrate your issue, you may do that here."
    validations:
      required: false
  - type: textarea
    id: logsDumps
    attributes:
      label: "Logs & Dumps"
      description: |
        Please feel free to attach any logs, block dumps, GSdump, etc here.
        If PCSX2 crashed, please post crash logs and the .dmp file (in a zip file) if appropriate.
        If your problem is graphical in nature it is highly recommended that you provide a GSdump. [GSdump Guide](https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump)
        **Note**: compared to retail games, SYSTEM2x6 games tend to have more debug logging left on them, therefore enabling the EE and IOP console on the debug tab might provide us with more information
    validations:
      required: false
  - type: input
    id: gameid
    attributes:
      label: please specify the gameid
      placeholder: "Example: NM00007"
    validations:
      required: true
  - type: input
    id: donglelabel
    attributes:
      label: If you know the dongle label code, specify it here. as there are several version/region of the dongles
      placeholder: "Example: ZGA1, Ver.A"
    validations:
      required: false
  - type: input
    id: disclabel
    attributes:
      label: If you know the disc/HDD code, specify it here. as certain games have different versions of it
      placeholder: "Example: ZGA DVD0"
    validations:
      required: false
